server:
  port: 18888

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: online_blackboard
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: U/kklUMxoX31LSie15kM+A==
    password: nUVSDE/dpoDMUCt44cSJJF0RYIPnoLxmldXgV88A/x4=
    url: jdbc:mysql://47.112.184.57:3308/blackboard
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  redis:
    host: 47.112.184.57

  servlet:
    multipart:
      max-file-size: 5MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true


---

spring:
  profile: dev
  uri_pre: http://47.112.184.57/

---

spring:
  profile: local
  uri_pre: http://localhost:18888/

